DROP DATABASE IF EXISTS dropdown_utility_ws;

CREATE DATABASE dropdown_utility_ws;

\c dropdown_utility_ws

CREATE TABLE IF NOT EXISTS countries (
  CountryID SERIAL PRIMARY KEY,
  CountryName VARCHAR(255) UNIQUE NOT NULL,
  CreatedTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS states (
  StateId SERIAL PRIMARY KEY,
  StateName VARCHAR(255) UNIQUE NOT NULL,
  countryId INT,
  CreatedTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(countryId) REFERENCES countries(CountryID)
);

CREATE TABLE IF NOT EXISTS cites (
  CityID SERIAL PRIMARY KEY,
  CityName VARCHAR(255) UNIQUE NOT NULL,
  StateId INT,
  CreatedTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(StateId) REFERENCES states(StateId)
);